### ISSUE TITLE
Scratch - Find by Title : Safe use of api-thetvdb 

### ISSUE THREAD

**Issue by fmunozse** [fmunozse/JTrackSeries#7]
Scratch - Find by Title : Safe use of api-thetvdb 

Currently api 1.8 throw nullpointer when notfound series, until https://github.com/Omertron/api-thetvdb/issues/17 is included in a version, the system should catch this nullpointer

**Comment by Omertron** [comment]
v1.9 of the API has been released. Hopefully this solves your issue :)
